language: node_js
node_js:
  - 8

cache: yarn
env:
  global:
    - CXX=g++-4.8
before_install:
  - npm install -g yarn codecov
  - '[ "${NPM_TOKEN+x}" ] && echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > $HOME/.npmrc || echo "Skipping .npmrc creation";'

jobs:
  include:
    - stage: test
      script:
       - yarn lint
       - yarn build
       - yarn test
       - codecov
    - stage: publish
      script:
       - yarn bump
       - npm publish
      if: type = push AND repo = enteam/enbase-cli AND branch = master